In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [5]:
train_df=pd.read_csv('train.csv')
test_df=pd.read_csv('test.csv')

In [7]:
train_df.corr().sort_values(by='SalePrice').head()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  \
ExterQual_TA     -0.312844 -0.188984  -0.025626      0.036360   -0.128084   
KitchenQual_TA   -0.273566 -0.182739  -0.010519      0.017080   -0.108876   
BsmtQual_TA      -0.222508 -0.150144  -0.024260      0.089043   -0.121785   
GarageFinish_Unf -0.253960 -0.081906  -0.052794      0.009897   -0.179000   
MasVnrType_None  -0.325566 -0.019491  -0.042266     -0.065965   -0.235217   

                  BsmtFinSF2  BsmtFullBath  BsmtHalfBath  BsmtUnfSF  \
ExterQual_TA        0.075127     -0.096217      0.076137  -0.282823   
KitchenQual_TA      0.061258     -0.102007      0.032787  -0.218945   
BsmtQual_TA         0.112889     -0.098442      0.067341  -0.122083   
GarageFinish_Unf    0.035795     -0.137590      0.053548  -0.128658   
MasVnrType_None     0.071079     -0.116849     -0.039176  -0.121476   

                  EnclosedPorch    ...      SaleType_ConLI  SaleType_ConLw  \
ExterQual_TA           0.130818    ...           -0.002482       -0.026643   
KitchenQual_TA         0.090396    ...           -0.012126       -0.012126   
BsmtQual_TA            0.193447    ...            0.018342        0.018342   
GarageFinish_Unf       0.158564    ...           -0.001712       -0.001712   
MasVnrType_None        0.156023    ...            0.000980        0.024834   

                  SaleType_New  SaleType_Oth  SaleType_WD  Street_Grvl  \
ExterQual_TA         -0.335148      0.035483     0.240734    -0.015958   
KitchenQual_TA       -0.274335      0.045067     0.178612     0.042386   
BsmtQual_TA          -0.265143     -0.010153     0.161940     0.028718   
GarageFinish_Unf     -0.238934     -0.007466     0.172316    -0.010569   
MasVnrType_None      -0.172209      0.037687     0.132540     0.009787   

                  Street_Pave  Utilities_AllPub  Utilities_NoSeWa  SalePrice  
ExterQual_TA         0.015958         -0.020472          0.020472  -0.589044  
KitchenQual_TA      -0.042386          0.026360         -0.026360  -0.519298  
BsmtQual_TA         -0.028718         -0.029266          0.029266  -0.452394  
GarageFinish_Unf     0.010569          0.022023         -0.022023  -0.410608  
MasVnrType_None     -0.009787          0.031521         -0.031521  -0.374468  

[5 rows x 271 columns]

In [9]:
X = train_df.loc[:,['OverallQual','GrLivArea','GarageCars']]

In [10]:
X.head()

OverallQual  GrLivArea  GarageCars
0          7.0     1710.0         2.0
1          6.0     1262.0         2.0
2          7.0     1786.0         2.0
3          7.0     1717.0         3.0
4          8.0     2198.0         3.0

In [11]:
y = train_df.loc[:,['SalePrice']].values
y[:10]

array([[208500],
       [181500],
       [223500],
       [140000],
       [250000],
       [143000],
       [307000],
       [200000],
       [129900],
       [118000]])

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [13]:
print(X.shape)
print(y.shape)

(1460, 3)
(1460, 1)


In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
lr.intercept_

array([-98652.53380432])

In [22]:
lr.coef_

array([[ 26032.22229536,     54.66365565,  21413.01669924]])

In [23]:
print('R^2')
print('train: %.3f' % Ir.score(X_train,y_train))
print('test: %.3f' % Ir.score(X_test,y_test))

R^2
train: 0.749
test: 0.717


In [24]:
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score

In [25]:
print('adjusted R^2')
print('train: %3f' % adjusted(Ir.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(Ir.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.748307
test : 0.715892


In [27]:
from sklearn.metrics import mean_squared_error as mse
print('RMSE')
print('train: %.3f' % (mse(y_train, Ir.predict(X_train)) ** 1/2))
print('test : %.3f' % (mse(y_test, Ir.predict(X_test)) ** 1/2))

RMSE
train: 766129069.822
test : 959989861.178


In [28]:
print("これでおっけい？かな")

これでおっけい？かな
